/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-08-17 02:24:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.User.mypage.addUser;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.net.URLEncoder;

public final class addUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1656316243398L));
    _jspx_dependants.put("jar:file:/C:/NCS/back/ppumting/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pm80/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.net.URLEncoder");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"../../../ico/favicon-32x32.png\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"signupcss/normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"signupcss/style.css?after\">\r\n");
      out.write("    <title>회원가입 | ppumting</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("      <header id=\"header\">\r\n");
      out.write("        <h1 class=\"logo\">PPUMTING | 회원가입<h1>\r\n");
      out.write("      </header>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div id=\"login_wrap\">\r\n");
      out.write("        <form class=\"login_form\" action=\"addUser\" method=\"post\">\r\n");
      out.write("        <div class=\"name_input\">\r\n");
      out.write("          <input type=\"text\" name=\"name\" placeholder=\"이름\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"ssn_input\">\r\n");
      out.write("          <input type=\"text\" name=\"ssn\" maxlength=\"6\" placeholder=\"주민번호 앞자리\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"phone_input\">\r\n");
      out.write("          <input type=\"tel\" name=\"phone\" maxlength=\"13\" placeholder=\"휴대전화\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"id_input\">\r\n");
      out.write("          <input type=\"text\" name=\"userId\" maxlength=\"13\" placeholder=\"아이디\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"pw_input\">\r\n");
      out.write("          <input type=\"password\" name=\"pw\" maxlength=\"13\" placeholder=\"비밀번호\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"addr_input\">\r\n");
      out.write("          <select name = \"addr1\" required>\r\n");
      out.write("			<option>지역 선택</option>\r\n");
      out.write("			<option>서울</option>\r\n");
      out.write("			<option>대구</option>\r\n");
      out.write("			<option>대전</option>\r\n");
      out.write("			<option>부산</option>\r\n");
      out.write("			<option>포항</option>\r\n");
      out.write("			<option>제주</option>\r\n");
      out.write("			<option>울산</option>\r\n");
      out.write("			<option>경기도</option>\r\n");
      out.write("			<option>강원도</option>\r\n");
      out.write("			<option>경상 북도</option>\r\n");
      out.write("			<option>경상 남도</option>\r\n");
      out.write("			<option>전라 북도</option>\r\n");
      out.write("			<option>전라 남도</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<input class=\"addr_input_1\"type = \"text\" name=\"addr2\" placeholder=\"상세 주소를 적어주세요\" required><br>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"login\" type=\"submit\">회원가입</button> \r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <footer id=\"footer\">\r\n");
      out.write("        <span class=\"text\">Copyright</span>\r\n");
      out.write("        <span class=\"corp\">© PPUMTING Corp.</span>\r\n");
      out.write("        <span class=\"text\">All Rights Reserved.</span>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--     <script>\r\n");
      out.write("    	function btn(){\r\n");
      out.write("    	   	if(true){\r\n");
      out.write("        		alert();\r\n");
      out.write("        	}\r\n");
      out.write("    	}\r\n");
      out.write(" \r\n");
      out.write("    </script> -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
